### ISSUE TITLE
Document input format

### ISSUE THREAD

**Issue by marnen** [tclh123/commits-graph#4]
I recently had occasion to try to make this into a Chrome extension (so I wouldn't have been able to use the Python script). Unfortunately, the input format is unclear and seems to be undocumented, so I wasn't able to figure it out. This tool draws beautiful graphs, but it's hard to work with if the input format is undocumented.

**Comment by rexsohw** [comment]
Hi Marnen, 

It's been a while for this question and I'm not sure if you have figured this out eventually.
I reached this project when I was looking for a simple tool to visualise my Git project. I'll try to answer your question in case someone else come to this as well.

## What's the input format?

The graph data is composed of an **array of nodes**.
As documented in the _commits_graphy.py_, each node is formatted as follows:
[
    sha, //commit hash
    [offest, branch], // Dot - x-axis offset position and branch it belongs to
    [
        [from, to, branch],  // Route 1 - The x-axis position from and to, and its corresponding branch
        [from, to, branch],  // Route 2
        [from, to, branch],
    ] // Route array (branches)
]

##How does the graph drawn?

Take a vertical graph as example. Let's call the rightest position as x-axis position 0.
It loops through the node array and draws from the top, one level by one level. For each iteration, 

1. Draw a dot based on the x-axis offset position and color it based on the assigned branch color. For example, [1,2] will be drawn at position 1 and branch 2 color.
2. Loop through the route array. For each route, draw a line **from** its x position **to** the x position of its y+1 position.

In fact, to draw the branches properly, each node will need to draw other branches even though it does not belong to them. (Otherwise, you won't see the long line for a branch)

<img width="146" alt="screen shot 2016-11-20 at 9 36 34 pm" src="https://cloud.githubusercontent.com/assets/4498345/20463188/74a5d9e2-af69-11e6-8060-8b1ec1e33497.png">

**Comment by tclh123** [comment]
https://github.com/tclh123/commits-graph/pull/5
